In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('bank-additional-full.csv', sep=';')

In [3]:
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon ...         1    999         0  nonexistent          1.1   
1   may         mon ...         1    999         0  nonexistent          1.1   
2   may         mon ...         1    999         0  nonexistent          1.1   
3   may         mon ...         1    999         0  nonexistent          1.1   
4   may         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [4]:
df.shape

(41188, 21)

In [5]:
df.replace({"unknown": np.nan}, inplace=True)

In [6]:
df.head()

age        job  marital    education default housing loan    contact month  \
0   56  housemaid  married     basic.4y      no      no   no  telephone   may   
1   57   services  married  high.school     NaN      no   no  telephone   may   
2   37   services  married  high.school      no     yes   no  telephone   may   
3   40     admin.  married     basic.6y      no      no   no  telephone   may   
4   56   services  married  high.school      no      no  yes  telephone   may   

  day_of_week ...  campaign  pdays  previous     poutcome emp.var.rate  \
0         mon ...         1    999         0  nonexistent          1.1   
1         mon ...         1    999         0  nonexistent          1.1   
2         mon ...         1    999         0  nonexistent          1.1   
3         mon ...         1    999         0  nonexistent          1.1   
4         mon ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [7]:
df.dropna(inplace=True, axis=0)

In [8]:
df.shape

(30488, 21)

In [9]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [10]:
df['job'].unique()

array(['housemaid', 'services', 'admin.', 'technician', 'blue-collar',
       'unemployed', 'retired', 'entrepreneur', 'management', 'student',
       'self-employed'], dtype=object)

In [11]:
dict_job = {'housemaid': 0, 'services': 1, 'admin.': 2, 'blue-collar': 3, 'technician': 4,
       'retired': 5, 'management': 6, 'unemployed': 7, 'self-employed': 8,
       'entrepreneur':9, 'student': 10}

In [12]:
df['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [13]:
dict_marr = {'married': 1, 'single': 0, 'divorced': 2}

In [14]:
df['education'].unique()

array(['basic.4y', 'high.school', 'basic.6y', 'professional.course',
       'basic.9y', 'university.degree', 'illiterate'], dtype=object)

In [15]:
dict_edu= {'basic.4y': 1, 'high.school': 4, 'basic.6y': 2, 'basic.9y':3,
       'professional.course': 5, 'university.degree': 6, 'illiterate': 0}

In [16]:
df['default'].unique()

array(['no', 'yes'], dtype=object)

In [17]:
dict_default = {'no': 0, 'yes': 1}

In [18]:
df['housing'].unique()

array(['no', 'yes'], dtype=object)

In [19]:
dict_hous = {'no': 0, 'yes': 1}

In [20]:
df['loan'].unique()

array(['no', 'yes'], dtype=object)

In [21]:
dict_loan = {'no': 0, 'yes': 1}

In [22]:
df['contact'].unique()

array(['telephone', 'cellular'], dtype=object)

In [23]:
dict_contact = {'telephone':0, 'cellular': 1}

In [24]:
df['month'].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'mar', 'apr', 'sep'], dtype=object)

In [25]:
dict_month={'may': 5, 'jun': 6, 'jul': 7, 'aug':8, 'oct': 10, 'nov': 11, 'dec': 12, 'mar': 3, 'apr': 4, 'sep': 9}

In [26]:
df['day_of_week'].unique()

array(['mon', 'tue', 'wed', 'thu', 'fri'], dtype=object)

In [27]:
dict_day_week = {'mon': 1, 'tue': 2, 'wed': 3, 'thu': 4, 'fri': 5}

In [28]:
df[df['duration'].isnull()]

Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

In [29]:
df['campaign'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 11, 18, 23, 14, 22, 25,
       17, 15, 20, 19, 39, 13, 42, 16, 28, 26, 32, 21, 24, 29, 31, 30, 35,
       41, 37, 27, 40, 43, 34, 33])

In [30]:
df['pdays'].unique()

array([999,   6,   4,   5,   1,   0,   3,  10,   7,   9,  11,   8,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27])

In [31]:
df['previous'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
df['poutcome'].unique()

array(['nonexistent', 'failure', 'success'], dtype=object)

In [33]:
dict_poutcome ={'nonexistent': 1, 'failure': 0, 'success': 2}

In [34]:
df['emp.var.rate'].unique()

array([ 1.1,  1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3. , -1.7, -1.1])

In [35]:
df['cons.price.idx'].unique()

array([ 93.994,  94.465,  93.918,  93.444,  93.798,  93.2  ,  92.756,
        92.843,  93.075,  92.893,  92.963,  92.469,  92.201,  92.379,
        92.431,  92.649,  92.713,  93.369,  93.749,  93.876,  94.055,
        94.215,  94.027,  94.199,  94.601,  94.767])

In [36]:
df['cons.conf.idx'].unique()

array([-36.4, -41.8, -42.7, -36.1, -40.4, -42. , -45.9, -50. , -47.1,
       -46.2, -40.8, -33.6, -31.4, -29.8, -26.9, -30.1, -33. , -34.8,
       -34.6, -40. , -39.8, -40.3, -38.3, -37.5, -49.5, -50.8])

In [37]:
df['euribor3m'].unique()

array([ 4.857,  4.856,  4.855,  4.859,  4.86 ,  4.858,  4.864,  4.865,
        4.866,  4.967,  4.961,  4.959,  4.958,  4.96 ,  4.962,  4.955,
        4.947,  4.956,  4.966,  4.963,  4.957,  4.968,  4.97 ,  4.965,
        4.964,  5.045,  5.   ,  4.936,  4.921,  4.918,  4.912,  4.827,
        4.794,  4.76 ,  4.733,  4.7  ,  4.663,  4.592,  4.474,  4.406,
        4.343,  4.286,  4.245,  4.223,  4.191,  4.153,  4.12 ,  4.076,
        4.021,  3.901,  3.879,  3.853,  3.816,  3.743,  3.669,  3.563,
        3.488,  3.428,  3.329,  3.282,  3.053,  1.811,  1.799,  1.778,
        1.757,  1.726,  1.703,  1.687,  1.663,  1.65 ,  1.64 ,  1.629,
        1.614,  1.602,  1.584,  1.56 ,  1.556,  1.548,  1.538,  1.531,
        1.52 ,  1.51 ,  1.498,  1.483,  1.479,  1.466,  1.453,  1.445,
        1.435,  1.423,  1.415,  1.41 ,  1.405,  1.406,  1.4  ,  1.392,
        1.384,  1.372,  1.365,  1.354,  1.344,  1.334,  1.327,  1.313,
        1.299,  1.291,  1.281,  1.266,  1.25 ,  1.244,  1.259,  1.264,
      

In [38]:
df['nr.employed'].unique()

array([ 5191. ,  5228.1,  5195.8,  5176.3,  5099.1,  5076.2,  5017.5,
        5023.5,  5008.7,  4991.6,  4963.6])

In [39]:
df['job'].replace(to_replace=dict_job, value=None, inplace=True, limit=None, regex=False, method='pad')

In [40]:
df['marital'].replace(to_replace=dict_marr, value=None, inplace=True, limit=None, regex=False, method='pad')

In [41]:
df['education'].replace(to_replace=dict_edu, value=None, inplace=True, limit=None, regex=False, method='pad')

In [42]:
df['housing'].replace(to_replace=dict_hous, value=None, inplace=True, limit=None, regex=False, method='pad')

In [43]:
df['loan'].replace(to_replace=dict_loan, value=None, inplace=True, limit=None, regex=False, method='pad')

In [44]:
df['contact'].replace(to_replace=dict_contact, value=None, inplace=True, limit=None, regex=False, method='pad')

In [45]:
df['month'].replace(to_replace=dict_month, value=None, inplace=True, limit=None, regex=False, method='pad')

In [46]:
df['day_of_week'].replace(to_replace=dict_day_week, value=None, inplace=True, limit=None, regex=False, method='pad')

In [47]:
df['poutcome'].replace(to_replace=dict_poutcome, value=None, inplace=True, limit=None, regex=False, method='pad')

In [48]:
df['default'].replace(to_replace=dict_default, value=None, inplace=True, limit=None, regex=False, method='pad')

In [49]:
df['y'].unique()

array(['no', 'yes'], dtype=object)

In [50]:
dict_y = {'no':0, 'yes':1}

In [51]:
df['y'].replace(to_replace=dict_y, value=None, inplace=True)

In [52]:
df['y'].value_counts()

0    26629
1     3859
Name: y, dtype: int64

In [53]:
df.head().transpose()

0         2         3         4         6
age               56.000    37.000    40.000    56.000    59.000
job                0.000     1.000     2.000     1.000     2.000
marital            1.000     1.000     1.000     1.000     1.000
education          1.000     4.000     2.000     4.000     5.000
default            0.000     0.000     0.000     0.000     0.000
housing            0.000     1.000     0.000     0.000     0.000
loan               0.000     0.000     0.000     1.000     0.000
contact            0.000     0.000     0.000     0.000     0.000
month              5.000     5.000     5.000     5.000     5.000
day_of_week        1.000     1.000     1.000     1.000     1.000
duration         261.000   226.000   151.000   307.000   139.000
campaign           1.000     1.000     1.000     1.000     1.000
pdays            999.000   999.000   999.000   999.000   999.000
previous           0.000     0.000     0.000     0.000     0.000
poutcome           1.000     1.000     1.000     1.000     1.000
emp.var.rate       1.100     1.100     1.100     1.100     1.100
cons.price.idx    93.994    93.994    93.994    93.994    93.994
cons.conf.idx    -36.400   -36.400   -36.400   -36.400   -36.400
euribor3m          4.857     4.857     4.857     4.857     4.857
nr.employed     5191.000  5191.000  5191.000  5191.000  5191.000
y                  0.000     0.000     0.000     0.000     0.000

In [54]:
df.to_csv("bank_additional_full_clean.csv", encoding='utf-8', index=False)

In [55]:
df = pd.read_csv("bank_additional_full_clean.csv")

In [56]:
to_scale = ['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 
            'euribor3m', 'nr.employed']

In [57]:
def data_scaling(df, scaling_col):
    df.loc[:,scaling_col] = (df.loc[:,scaling_col]-df.loc[:, scaling_col].mean())/df.loc[:, scaling_col].std()
    return df   

In [58]:
df_sc = data_scaling(df, to_scale)

In [60]:
df_sc.head()

age  job  marital  education  default  housing  loan  contact  month  \
0  1.642226    0        1          1        0        0     0        0      5   
1 -0.196449    1        1          4        0        1     0        0      5   
2  0.093868    2        1          2        0        0     0        0      5   
3  1.642226    1        1          4        0        0     1        0      5   
4  1.932543    2        1          5        0        0     0        0      5   

   day_of_week ...  campaign     pdays  previous  poutcome  emp.var.rate  \
0            1 ... -0.559326  0.211884  -0.37161         1      0.727466   
1            1 ... -0.559326  0.211884  -0.37161         1      0.727466   
2            1 ... -0.559326  0.211884  -0.37161         1      0.727466   
3            1 ... -0.559326  0.211884  -0.37161         1      0.727466   
4            1 ... -0.559326  0.211884  -0.37161         1      0.727466   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0        0.804082       0.877437   0.786089     0.401641  0  
1        0.804082       0.877437   0.786089     0.401641  0  
2        0.804082       0.877437   0.786089     0.401641  0  
3        0.804082       0.877437   0.786089     0.401641  0  
4        0.804082       0.877437   0.786089     0.401641  0  

[5 rows x 21 columns]

In [61]:
df_sc.to_csv("bank_additional_full_clean_scaled.csv", encoding='utf-8', index=False)