In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('./bank-additional/bank-additional-full.csv', sep=';')

In [3]:
df.head()

age        job  marital    education  default housing loan    contact  \
0   56  housemaid  married     basic.4y       no      no   no  telephone   
1   57   services  married  high.school  unknown      no   no  telephone   
2   37   services  married  high.school       no     yes   no  telephone   
3   40     admin.  married     basic.6y       no      no   no  telephone   
4   56   services  married  high.school       no      no  yes  telephone   

  month day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0   may         mon  ...         1    999         0  nonexistent          1.1   
1   may         mon  ...         1    999         0  nonexistent          1.1   
2   may         mon  ...         1    999         0  nonexistent          1.1   
3   may         mon  ...         1    999         0  nonexistent          1.1   
4   may         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [4]:
df.shape

(41188, 21)

In [5]:
df.replace({"unknown": np.nan}, inplace=True)

In [6]:
df.head()

age        job  marital    education default housing loan    contact month  \
0   56  housemaid  married     basic.4y      no      no   no  telephone   may   
1   57   services  married  high.school     NaN      no   no  telephone   may   
2   37   services  married  high.school      no     yes   no  telephone   may   
3   40     admin.  married     basic.6y      no      no   no  telephone   may   
4   56   services  married  high.school      no      no  yes  telephone   may   

  day_of_week  ...  campaign  pdays  previous     poutcome emp.var.rate  \
0         mon  ...         1    999         0  nonexistent          1.1   
1         mon  ...         1    999         0  nonexistent          1.1   
2         mon  ...         1    999         0  nonexistent          1.1   
3         mon  ...         1    999         0  nonexistent          1.1   
4         mon  ...         1    999         0  nonexistent          1.1   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed   y  
0          93.994          -36.4      4.857       5191.0  no  
1          93.994          -36.4      4.857       5191.0  no  
2          93.994          -36.4      4.857       5191.0  no  
3          93.994          -36.4      4.857       5191.0  no  
4          93.994          -36.4      4.857       5191.0  no  

[5 rows x 21 columns]

In [7]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [8]:
df['job'].isnull().sum()

330

In [9]:
for col in df.columns:
    null_sum = df[col].isnull().sum()
    print(f'{col} null: ',null_sum)

age null:  0
job null:  330
marital null:  80
education null:  1731
default null:  8597
housing null:  990
loan null:  990
contact null:  0
month null:  0
day_of_week null:  0
duration null:  0
campaign null:  0
pdays null:  0
previous null:  0
poutcome null:  0
emp.var.rate null:  0
cons.price.idx null:  0
cons.conf.idx null:  0
euribor3m null:  0
nr.employed null:  0
y null:  0


In [10]:
len(df)

41188

In [11]:
df.dropna(inplace=True, axis=0)

In [12]:
df.shape

(30488, 21)

In [13]:
for col in df.columns:
    null_sum = df[col].isnull().sum()
    print(f'{col} null: ',null_sum)

age null:  0
job null:  0
marital null:  0
education null:  0
default null:  0
housing null:  0
loan null:  0
contact null:  0
month null:  0
day_of_week null:  0
duration null:  0
campaign null:  0
pdays null:  0
previous null:  0
poutcome null:  0
emp.var.rate null:  0
cons.price.idx null:  0
cons.conf.idx null:  0
euribor3m null:  0
nr.employed null:  0
y null:  0


In [14]:
job_titles = df['job'].unique()
job_titles

array(['housemaid', 'services', 'admin.', 'technician', 'blue-collar',
       'unemployed', 'retired', 'entrepreneur', 'management', 'student',
       'self-employed'], dtype=object)

In [15]:
dict_job = {'housemaid': 0, 'services': 1, 'admin.': 2, 'blue-collar': 3, 'technician': 4,
       'retired': 5, 'management': 6, 'unemployed': 7, 'self-employed': 8,
       'entrepreneur':9, 'student': 10}

In [17]:
import pickle

f = open("job_title_dictionary.pkl","wb")

pickle.dump(dict_job,f)

f.close()

In [18]:
with open("job_title_dictionary.pkl", 'rb') as f:
    job_title_dic = pickle.load(f)
job_title_dic

{'housemaid': 0,
 'services': 1,
 'admin.': 2,
 'blue-collar': 3,
 'technician': 4,
 'retired': 5,
 'management': 6,
 'unemployed': 7,
 'self-employed': 8,
 'entrepreneur': 9,
 'student': 10}

In [19]:
marital_status = df['marital'].unique()
marital_status

array(['married', 'single', 'divorced'], dtype=object)

In [20]:
dict_marr = {'single': 0, 'divorced': 1, 'married': 2 }

In [21]:
f = open("marital_status.pkl","wb")
pickle.dump(dict_marr, f)
f.close()

In [22]:
with open("marital_status.pkl", 'rb') as f:
    marital_status_dic = pickle.load(f)
marital_status_dic

{'single': 0, 'divorced': 1, 'married': 2}

In [23]:
edu = df['education'].unique()
edu

array(['basic.4y', 'high.school', 'basic.6y', 'professional.course',
       'basic.9y', 'university.degree', 'illiterate'], dtype=object)

In [24]:
edu_dict = {'basic.4y': 1, 'high.school': 4, 'basic.6y': 2, 'basic.9y':3,
       'professional.course': 5, 'university.degree': 6, 'illiterate': 0}

In [25]:
f = open("education_status_dic.pkl","wb")
pickle.dump(edu_dict, f)
f.close()

In [26]:
with open("education_status_dic.pkl", 'rb') as f:
    edu_status_dic = pickle.load(f)
edu_status_dic

{'basic.4y': 1,
 'high.school': 4,
 'basic.6y': 2,
 'basic.9y': 3,
 'professional.course': 5,
 'university.degree': 6,
 'illiterate': 0}

In [27]:
df['default'].unique()

array(['no', 'yes'], dtype=object)

In [28]:
dict_default = {'no': 0, 'yes': 1}

In [29]:
f = open("default_status_dic.pkl","wb")
pickle.dump(dict_default, f)
f.close()

In [30]:
with open("default_status_dic.pkl", 'rb') as f:
    dict_default = pickle.load(f)
dict_default

{'no': 0, 'yes': 1}

In [31]:
df['housing'].unique()

array(['no', 'yes'], dtype=object)

In [32]:
dict_housing = {'no': 0, 'yes': 1}

In [33]:
f = open("housing_status_dic.pkl","wb")
pickle.dump(dict_housing, f)
f.close()

In [34]:
with open("housing_status_dic.pkl", 'rb') as f:
    dict_housing = pickle.load(f)
dict_housing

{'no': 0, 'yes': 1}

In [35]:
df['loan'].unique()

array(['no', 'yes'], dtype=object)

In [36]:
dict_loan = {'no': 0, 'yes': 1}

In [37]:
f = open("loan_status_dic.pkl","wb")
pickle.dump(dict_loan, f)
f.close()

In [38]:
with open("loan_status_dic.pkl", 'rb') as f:
    dict_loan = pickle.load(f)
dict_loan

{'no': 0, 'yes': 1}

In [39]:
df['contact'].unique()

array(['telephone', 'cellular'], dtype=object)

In [40]:
dict_contact = {'telephone':0, 'cellular': 1}

In [41]:
f = open("contact_status_dic.pkl","wb")
pickle.dump(dict_contact, f)
f.close()

In [42]:
with open("contact_status_dic.pkl", 'rb') as f:
    dict_contact = pickle.load(f)
dict_contact

{'telephone': 0, 'cellular': 1}

In [43]:
dict_month={'jan':1, 'feb':2, 'mar':3, 'apr':4, 'may':5, 'jun':6, 
            'jul':7, 'aug':8, 'sep':9, 'oct':10, 'nov':11, 'dec':12}

In [44]:
f = open("month_dic.pkl","wb")
pickle.dump(dict_month, f)
f.close()

In [45]:
with open("month_dic.pkl", 'rb') as f:
    dict_month = pickle.load(f)
dict_month

{'jan': 1,
 'feb': 2,
 'mar': 3,
 'apr': 4,
 'may': 5,
 'jun': 6,
 'jul': 7,
 'aug': 8,
 'sep': 9,
 'oct': 10,
 'nov': 11,
 'dec': 12}

In [46]:
df['day_of_week'].unique()

array(['mon', 'tue', 'wed', 'thu', 'fri'], dtype=object)

In [47]:
dict_day_week = {'sun': 0, 'mon': 1, 'tue': 2, 'wed': 3, 'thu': 4, 'fri': 5, 'Sat': 6}

In [48]:
f = open("day_of_week_dic.pkl","wb")
pickle.dump(dict_day_week, f)
f.close()

In [49]:
with open("day_of_week_dic.pkl", 'rb') as f:
    dict_day_week = pickle.load(f)
dict_day_week

{'sun': 0, 'mon': 1, 'tue': 2, 'wed': 3, 'thu': 4, 'fri': 5, 'Sat': 6}

In [50]:
df['campaign'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 11, 18, 23, 14, 22, 25,
       17, 15, 20, 19, 39, 13, 42, 16, 28, 26, 32, 21, 24, 29, 31, 30, 35,
       41, 37, 27, 40, 43, 34, 33])

In [51]:
df['pdays'].unique()

array([999,   6,   4,   5,   1,   0,   3,  10,   7,   9,  11,   8,   2,
        12,  13,  14,  15,  16,  21,  17,  18,  22,  25,  26,  19,  27])

In [52]:
df['previous'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
df['poutcome'].unique()

array(['nonexistent', 'failure', 'success'], dtype=object)

In [54]:
dict_poutcome ={'nonexistent': 1, 'failure': 0, 'success': 2}
f = open("previous_outcome_dic.pkl","wb")
pickle.dump(dict_poutcome, f)
f.close()

In [55]:
with open("previous_outcome_dic.pkl", 'rb') as f:
    dict_poutcome = pickle.load(f)
dict_poutcome

{'nonexistent': 1, 'failure': 0, 'success': 2}

In [56]:
df['emp.var.rate'].unique()

array([ 1.1,  1.4, -0.1, -0.2, -1.8, -2.9, -3.4, -3. , -1.7, -1.1])

In [57]:
df['cons.price.idx'].unique()

array([93.994, 94.465, 93.918, 93.444, 93.798, 93.2  , 92.756, 92.843,
       93.075, 92.893, 92.963, 92.469, 92.201, 92.379, 92.431, 92.649,
       92.713, 93.369, 93.749, 93.876, 94.055, 94.215, 94.027, 94.199,
       94.601, 94.767])

In [58]:
df['cons.conf.idx'].unique()

array([-36.4, -41.8, -42.7, -36.1, -40.4, -42. , -45.9, -50. , -47.1,
       -46.2, -40.8, -33.6, -31.4, -29.8, -26.9, -30.1, -33. , -34.8,
       -34.6, -40. , -39.8, -40.3, -38.3, -37.5, -49.5, -50.8])

In [59]:
df['euribor3m'].unique()[:10]

array([4.857, 4.856, 4.855, 4.859, 4.86 , 4.858, 4.864, 4.865, 4.866,
       4.967])

In [60]:
df['nr.employed'].unique()

array([5191. , 5228.1, 5195.8, 5176.3, 5099.1, 5076.2, 5017.5, 5023.5,
       5008.7, 4991.6, 4963.6])

In [61]:
df['job'].replace(to_replace=job_title_dic, value=None, inplace=True, limit=None, regex=False, method='pad')

In [62]:
df['marital'].replace(to_replace=marital_status_dic, value=None, inplace=True, limit=None, regex=False, method='pad')

In [63]:
df['education'].replace(to_replace=edu_status_dic, value=None, inplace=True, limit=None, regex=False, method='pad')

In [64]:
df['housing'].replace(to_replace=dict_housing, value=None, inplace=True, limit=None, regex=False, method='pad')

In [65]:
df['loan'].replace(to_replace=dict_loan, value=None, inplace=True, limit=None, regex=False, method='pad')

In [66]:
df['contact'].replace(to_replace=dict_contact, value=None, inplace=True, limit=None, regex=False, method='pad')

In [67]:
df['month'].replace(to_replace=dict_month, value=None, inplace=True, limit=None, regex=False, method='pad')

In [68]:
df['day_of_week'].replace(to_replace=dict_day_week, value=None, inplace=True, limit=None, regex=False, method='pad')

In [69]:
df['poutcome'].replace(to_replace=dict_poutcome, value=None, inplace=True, limit=None, regex=False, method='pad')

In [70]:
df['default'].replace(to_replace=dict_default, value=None, inplace=True, limit=None, regex=False, method='pad')

In [71]:
df['y'].unique()

array(['no', 'yes'], dtype=object)

In [72]:
dict_y = {'no':0, 'yes':1}

In [73]:
df['y'].replace(to_replace=dict_y, inplace=True)

In [74]:
df['y'].value_counts()

0    26629
1     3859
Name: y, dtype: int64

In [75]:
df.head(10).transpose()

0         2         3         4         6         8   \
age               56.000    37.000    40.000    56.000    59.000    24.000   
job                0.000     1.000     2.000     1.000     2.000     4.000   
marital            2.000     2.000     2.000     2.000     2.000     0.000   
education          1.000     4.000     2.000     4.000     5.000     5.000   
default            0.000     0.000     0.000     0.000     0.000     0.000   
housing            0.000     1.000     0.000     0.000     0.000     1.000   
loan               0.000     0.000     0.000     1.000     0.000     0.000   
contact            0.000     0.000     0.000     0.000     0.000     0.000   
month              5.000     5.000     5.000     5.000     5.000     5.000   
day_of_week        1.000     1.000     1.000     1.000     1.000     1.000   
duration         261.000   226.000   151.000   307.000   139.000   380.000   
campaign           1.000     1.000     1.000     1.000     1.000     1.000   
pdays            999.000   999.000   999.000   999.000   999.000   999.000   
previous           0.000     0.000     0.000     0.000     0.000     0.000   
poutcome           1.000     1.000     1.000     1.000     1.000     1.000   
emp.var.rate       1.100     1.100     1.100     1.100     1.100     1.100   
cons.price.idx    93.994    93.994    93.994    93.994    93.994    93.994   
cons.conf.idx    -36.400   -36.400   -36.400   -36.400   -36.400   -36.400   
euribor3m          4.857     4.857     4.857     4.857     4.857     4.857   
nr.employed     5191.000  5191.000  5191.000  5191.000  5191.000  5191.000   
y                  0.000     0.000     0.000     0.000     0.000     0.000   

                      9         11        12        13  
age               25.000    25.000    29.000    57.000  
job                1.000     1.000     3.000     0.000  
marital            0.000     0.000     0.000     1.000  
education          4.000     4.000     4.000     1.000  
default            0.000     0.000     0.000     0.000  
housing            1.000     1.000     0.000     1.000  
loan               0.000     0.000     1.000     0.000  
contact            0.000     0.000     0.000     0.000  
month              5.000     5.000     5.000     5.000  
day_of_week        1.000     1.000     1.000     1.000  
duration          50.000   222.000   137.000   293.000  
campaign           1.000     1.000     1.000     1.000  
pdays            999.000   999.000   999.000   999.000  
previous           0.000     0.000     0.000     0.000  
poutcome           1.000     1.000     1.000     1.000  
emp.var.rate       1.100     1.100     1.100     1.100  
cons.price.idx    93.994    93.994    93.994    93.994  
cons.conf.idx    -36.400   -36.400   -36.400   -36.400  
euribor3m          4.857     4.857     4.857     4.857  
nr.employed     5191.000  5191.000  5191.000  5191.000  
y                  0.000     0.000     0.000     0.000

In [76]:
df.to_csv("bank_additional_full_clean.csv", encoding='utf-8', index=False)

In [85]:
df = pd.read_csv("bank_additional_full_clean.csv")

In [80]:
cols_for_normalization = ['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 
            'euribor3m', 'nr.employed']

In [91]:
print(df.loc[:, cols_for_normalization].mean())
df.loc[:, cols_for_normalization].mean().to_csv("Means_for_normalization.csv", index=True)

age                 39.030012
duration           259.484092
campaign             2.521451
pdays              956.332295
previous             0.194273
emp.var.rate        -0.071510
cons.price.idx      93.523311
cons.conf.idx      -40.602263
euribor3m            3.459938
nr.employed       5160.813409
dtype: float64


In [92]:
pd.read_csv("Means_for_normalization.csv")

Unnamed: 0            0
0             age    39.030012
1        duration   259.484092
2        campaign     2.521451
3           pdays   956.332295
4        previous     0.194273
5    emp.var.rate    -0.071510
6  cons.price.idx    93.523311
7   cons.conf.idx   -40.602263
8       euribor3m     3.459938
9     nr.employed  5160.813409

In [93]:
print(df.loc[:, cols_for_normalization].std())
df.loc[:, cols_for_normalization].std().to_csv("Std_for_normalization.csv", index=True)

age                10.333529
duration          261.714262
campaign            2.720150
pdays             201.373292
previous            0.522788
emp.var.rate        1.610399
cons.price.idx      0.585374
cons.conf.idx       4.789249
euribor3m           1.777231
nr.employed        75.158065
dtype: float64


In [95]:
pd.read_csv("Std_for_normalization.csv")

Unnamed: 0           0
0             age   10.333529
1        duration  261.714262
2        campaign    2.720150
3           pdays  201.373292
4        previous    0.522788
5    emp.var.rate    1.610399
6  cons.price.idx    0.585374
7   cons.conf.idx    4.789249
8       euribor3m    1.777231
9     nr.employed   75.158065

In [96]:
def data_std_normalization(df, cols):
    avg = df.loc[:, cols].mean()
    std = df.loc[:, cols].std()
    df.loc[:, cols] = (df.loc[:, cols]- avg)/std
    return df, avg, std   

In [97]:
df_norm, df_mean, df_std = data_std_normalization(df, cols_for_normalization)

In [98]:
df_mean

age                 39.030012
duration           259.484092
campaign             2.521451
pdays              956.332295
previous             0.194273
emp.var.rate        -0.071510
cons.price.idx      93.523311
cons.conf.idx      -40.602263
euribor3m            3.459938
nr.employed       5160.813409
dtype: float64

In [99]:
df_std

age                10.333529
duration          261.714262
campaign            2.720150
pdays             201.373292
previous            0.522788
emp.var.rate        1.610399
cons.price.idx      0.585374
cons.conf.idx       4.789249
euribor3m           1.777231
nr.employed        75.158065
dtype: float64

In [100]:
df_norm.head()

age  job  marital  education  default  housing  loan  contact  month  \
0  1.642226    0        2          1        0        0     0        0      5   
1 -0.196449    1        2          4        0        1     0        0      5   
2  0.093868    2        2          2        0        0     0        0      5   
3  1.642226    1        2          4        0        0     1        0      5   
4  1.932543    2        2          5        0        0     0        0      5   

   day_of_week  ...  campaign     pdays  previous  poutcome  emp.var.rate  \
0            1  ... -0.559326  0.211884  -0.37161         1      0.727466   
1            1  ... -0.559326  0.211884  -0.37161         1      0.727466   
2            1  ... -0.559326  0.211884  -0.37161         1      0.727466   
3            1  ... -0.559326  0.211884  -0.37161         1      0.727466   
4            1  ... -0.559326  0.211884  -0.37161         1      0.727466   

   cons.price.idx  cons.conf.idx  euribor3m  nr.employed  y  
0        0.804082       0.877437   0.786089     0.401641  0  
1        0.804082       0.877437   0.786089     0.401641  0  
2        0.804082       0.877437   0.786089     0.401641  0  
3        0.804082       0.877437   0.786089     0.401641  0  
4        0.804082       0.877437   0.786089     0.401641  0  

[5 rows x 21 columns]

In [101]:
df_norm.to_csv("bank_additional_full_clean_normalized.csv", encoding='utf-8', index=False)